### ISSUE TITLE
Undefined property: Barryvdh\Queue\Jobs\AsyncJob::$deleted

### ISSUE THREAD

**Issue by jrura18** [barryvdh/laravel-async-queue#31]
Hello,
I have little problem, i don't understand why get this error in line 49 AsyncJoob.php. Somebody tell me about this error?
(Undefined property: Barryvdh\Queue\Jobs\AsyncJob::$deleted)

**Comment by barryvdh** [comment]
What Laravel version? 4.0?

**Comment by jrura18** [comment]
Yes is 4.0

**Comment by barryvdh** [comment]
Should be fixed in above commit.

**Comment by jrura18** [comment]
Ok, I will refresh library

**Comment by jrura18** [comment]
It works, Thank You :)

Close Issue
