### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by hadi77makkawi** [barryvdh/laravel-async-queue#36]
When i try to install using composer require barryvdh/laravel-async-queue

Am getting these errors

 - don't install illuminate/console v5.0.4|don't install laravel/framework v5.1.1
 - Installation request for laravel/framework 5.1.1 -> satisfiable by laravel/framework[v5.1.1].
 - Installation request for barryvdh/laravel-async-queue 0.3.* -> satisfiable by barryvdh/laravel-async-queue[v0.3.0, v0.3.1].

**Comment by GrahamCampbell** [comment]
You need to install `0.4.*`/

**Comment by vcalaelen** [comment]
Yes, this solves the problem, can you please update the README file for the 0.4.* branch.

**Comment by barryvdh** [comment]
Tagged 0.4.0 and updated default branch
