### ISSUE TITLE
Job is not executed

### ISSUE THREAD

**Issue by natsu90** [barryvdh/laravel-async-queue#40]
I'm doing delete & insert to a table report; listening to every change row of another table. It's working fine on first update. On second update, the event is triggered, there is queue in laq_async_queue table with status=2 but it stuck there, not executed, no error log at all. Any idea? Can it be not allowed same payload in queue?

edit: Can not be error in my code since it'll throw error if there's a syntax error.

edit: I executed `php artisan queue:async {jobId}` myself with no problem.

**Comment by barryvdh** [comment]
What version are you on? Can you check with 0.4? (Laravel 5)

**Comment by natsu90** [comment]
Sorry for the long response. I just debug again and found the problem; it's my permission issue in logging function. Sorry.
