### ISSUE TITLE
Laravel 5.1 ErrorException in AsyncConnector.php line 22: Undefined index: table

### ISSUE THREAD

**Issue by annanoell** [barryvdh/laravel-async-queue#42]
The Async queue is working fine in my staging server, and it was working on my development machine yestarday just fine. 

The thing is that today I'm getting an error: 

`ErrorException in AsyncConnector.php line 22:
Undefined index: table`

I really don't know why this is suddenly happening because I didn't change nothing on the project and I cannot find information for that error.

Thank you.

**Comment by barryvdh** [comment]
Did you update to a new minor release?

See new readme: https://github.com/barryvdh/laravel-async-queue/commit/1c0ed34eb483df5893ab838867e754dcd7906216

**Comment by annanoell** [comment]
Oh great, it's working now. 

I'm using ' "barryvdh/laravel-async-queue": "0.4.x" ' .
Maybe I should use a fixed version and just update when you release a major version?
