### ISSUE TITLE
Going to support 5.4?

### ISSUE THREAD

**Issue by CBox** [barryvdh/laravel-async-queue#64]
Hey there,

Is there any plan to support 5.4?

Thanks!

**Comment by barryvdh** [comment]
Not actively for now, but open for PR. Whats the problem?

**Comment by CBox** [comment]
I'm getting:
ErrorException in AsyncQueue.php line 12:
Declaration of Barryvdh\Queue\AsyncQueue::pushToDatabase() should be compatible with Illuminate\Queue\DatabaseQueue::pushToDatabase($queue, $payload, $delay = 0, $attempts = 0)

Any idea?

**Comment by mohank28** [comment]
Hi im getting this error and iam using Laravel 5.4.16
Using version ^0.5.0 for barryvdh/laravel-async-queue
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barryvdh/laravel-async-queue ^0.5.0 -> satisfiable by barryvdh/laravel-async-queue[v0.5.0].
    - Conclusion: remove laravel/framework v5.4.16
    - Conclusion: don't install laravel/framework v5.4.16
    - barryvdh/laravel-async-queue v0.5.0 requires illuminate/support 5.3.x -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.16
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.16
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.16
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.16
    - Installation request for laravel/framework (locked at v5.4.16, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.16].

**Comment by barryvdh** [comment]
Can you try with `v0.6.0`?

**Comment by mohank28** [comment]
Hi @barryvdh, thanks for the 5.4 support,
Here is my config,
`'async' => [
        'driver' => 'async',
        'table' => 'jobs',
        'queue' => 'default',
        'expire' => 60,
        'binary' => '/usr/bin/php7.0',
        'binary_args' => '',
        ],`

Still im not getting queue process in background. Pls tell about binary args.

**Comment by barryvdh** [comment]
You usually don't need binary and binary_args at all. Do you have any errors in your logs?

**Comment by mohank28** [comment]
Yes, here is my log,
`[2017-04-04 12:55:11] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Queue\Worker::getManager() in /home/vagrant/Code/summerside/vendor/barryvdh/laravel-async-queue/src/Console/AsyncCommand.php:72
Stack trace:
#0 /home/vagrant/Code/summerside/vendor/barryvdh/laravel-async-queue/src/Console/AsyncCommand.php(59): Barryvdh\Queue\Console\AsyncCommand->processJob('async', '5', Object(Illuminate\Queue\WorkerOptions))
#1 [internal function]: Barryvdh\Queue\Console\AsyncCommand->fire(Object(Illuminate\Queue\WorkerOptions))
#2 /home/vagrant/Code/summerside/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#3 /home/vagrant/Code/summerside/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /home/vagrant/Code/summerside/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#5 /home/vagrant/Code/summerside/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#6 /home/vagrant/Code/summerside/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#7 /home/vagrant/Code/summerside/vendor/symfony/console/Command/Command.php(265): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#8 /home/vagrant/Code/summerside/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#9 /home/vagrant/Code/summerside/vendor/symfony/console/Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/vagrant/Code/summerside/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Barryvdh\Queue\Console\AsyncCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/vagrant/Code/summerside/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/vagrant/Code/summerside/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/vagrant/Code/summerside/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  `

**Comment by barryvdh** [comment]
Can you also update Laravel to the latest 5.4 version? (.17 I think)

**Comment by mohank28** [comment]
@barryvdh Thanks! It works with Laravel 5.4.17.

**Comment by CBox** [comment]
@barryvdh thanks man! working for me too.
