### ISSUE TITLE
Laravel 5.5 Support?

### ISSUE THREAD

**Issue by oriceon** [barryvdh/laravel-async-queue#68]
Can you update composer please?

**Comment by barryvdh** [comment]
Can you test with `0.6.x@dev`?

**Comment by oriceon** [comment]
In AsyncCommand change fire() to handle() method. And all`s fine!
Thanks.

**Comment by barryvdh** [comment]
Can you submit a PR?

**Comment by oriceon** [comment]
Sure. I did.

**Comment by barryvdh** [comment]
I've added branch alias for 0.7, Perhaps we need to add this too
https://laravel-news.com/package-auto-discovery

**Comment by oriceon** [comment]
Sure. Make a change for that. And don`t forget to push a release. Thank you.

**Comment by barryvdh** [comment]
done
