### ISSUE TITLE
Doesn't work with Laravel 5.6?

### ISSUE THREAD

**Issue by AdnanMoghal** [barryvdh/laravel-async-queue#73]
composer install command gives the following error with composer.json line:

  "barryvdh/laravel-async-queue": "^0.6.0",

Error:

Installation request for barryvdh/laravel-async-queue ^0.6.0 -> satisfiable by barryvdh/laravel-async-queue[v0.6.0].
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1
    - barryvdh/laravel-async-queue v0.6.0 requires illuminate/support 5.4.x -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].

**Comment by AliHaider26** [comment]
issue fixed ..

**Comment by barryvdh** [comment]
Tagged a new release
