### ISSUE TITLE
Please support laravel 5.6.*

### ISSUE THREAD

**Issue by janisbarons** [barryvdh/laravel-async-queue#76]
>  Problem 1
>     - Installation request for barryvdh/laravel-async-queue ^0.7.0 -> satisfiable by barryvdh/laravel-async-queue[v0.7.0].
>     - Conclusion: remove laravel/framework v5.6.16
>     - Conclusion: don't install laravel/framework v5.6.16
> 
Please support newest laravel framework.

Thanks!

**Comment by Devamit2016** [comment]
me too facing same problem

**Comment by barryvdh** [comment]
Tagged a new release
